import {
  Activity,
  BadgeDollarSign,
  BarChart3,
  Bell,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  Cog,
  CreditCard,
  FileArchive,
  FileText,
  GitCompareArrows,
  HandCoins,
  Home,
  Landmark,
  Megaphone,
  Package,
  Receipt,
  ShieldCheck,
  UserCircle,
  Users,
  WalletCards,
} from "lucide-react";
import type { NavigationItem } from "../../../app/navigation/navigationTypes";

export const adminNavigation: NavigationItem[] = [
  { label: "Inicio", path: "/admin/inicio", icon: Home, end: true },
  { label: "CRM", path: "/admin/crm", icon: BriefcaseBusiness },
  { label: "Cotizaciones", path: "/admin/cotizaciones", icon: ClipboardList },
  { label: "Obras", path: "/admin/obras", icon: Building2 },
  { label: "Trabajadores", path: "/admin/trabajadores", icon: Users },
  { label: "Control horario", path: "/admin/control-horario", icon: Clock3 },
  { label: "Partes diarios", path: "/admin/partes-diarios", icon: ClipboardCheck },
  { label: "Finanzas", path: "/admin/finanzas", icon: BadgeDollarSign },
  { label: "Facturas", path: "/admin/facturas", icon: Receipt },
  { label: "Gastos", path: "/admin/gastos", icon: HandCoins },
  { label: "Activos", path: "/admin/activos", icon: Package },
  { label: "Pasivos", path: "/admin/pasivos", icon: WalletCards },
  { label: "Marketing", path: "/admin/marketing", icon: Megaphone },
  { label: "Documentos", path: "/admin/documentos", icon: FileArchive },
  { label: "Notificaciones", path: "/admin/notificaciones", icon: Bell },
  { label: "Informes", path: "/admin/informes", icon: BarChart3 },
  { label: "Usuarios y roles", path: "/admin/usuarios-y-roles", icon: ShieldCheck },
  { label: "Configuracion", path: "/admin/configuracion", icon: Cog },
  { label: "Validacion sectorial", path: "/admin/validacion-sectorial", icon: GitCompareArrows },
  { label: "Auditoria", path: "/admin/auditoria", icon: Activity },
];

export const managerNavigation: NavigationItem[] = [
  { label: "Inicio", path: "/manager/inicio", icon: Home, end: true },
  { label: "Clientes", path: "/manager/clientes", icon: BriefcaseBusiness },
  { label: "Cotizaciones", path: "/manager/cotizaciones", icon: ClipboardList },
  { label: "Obras", path: "/manager/obras", icon: Building2 },
  { label: "Trabajadores", path: "/manager/trabajadores", icon: Users },
  { label: "Control horario", path: "/manager/control-horario", icon: Clock3 },
  { label: "Partes diarios", path: "/manager/partes-diarios", icon: ClipboardCheck },
  { label: "Facturas", path: "/manager/facturas", icon: Receipt },
  { label: "Cobros", path: "/manager/cobros", icon: Landmark },
  { label: "Gastos", path: "/manager/gastos", icon: HandCoins },
  { label: "Marketing", path: "/manager/marketing", icon: Megaphone },
  { label: "Documentos", path: "/manager/documentos", icon: FileText },
  { label: "Notificaciones", path: "/manager/notificaciones", icon: Bell },
  { label: "Informes operativos", path: "/manager/informes-operativos", icon: BarChart3 },
];

export const workerNavigation: NavigationItem[] = [
  { label: "Inicio", path: "/worker/inicio", icon: Home, end: true },
  { label: "Mi jornada", path: "/worker/mi-jornada", icon: CalendarClock },
  { label: "Asistencia", path: "/worker/asistencia", icon: Clock3 },
  { label: "Trabajos asignados", path: "/worker/trabajos-asignados", icon: Building2 },
  { label: "Pruebas de trabajo", path: "/worker/pruebas-de-trabajo", icon: ClipboardCheck },
  { label: "Historial de horas", path: "/worker/historial-de-horas", icon: BarChart3 },
  { label: "Notificaciones", path: "/worker/notificaciones", icon: Bell },
  { label: "Mi perfil", path: "/worker/mi-perfil", icon: UserCircle },
];
