const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 42;

const TEMPLATE_STYLES = {
  estimate_classic_blue: {
    accent: [0.03, 0.18, 0.36],
    secondary: [0.94, 0.55, 0.06],
    soft: [0.93, 0.96, 0.99],
    title: "classic",
  },
  estimate_cleaning_teal: {
    accent: [0.39, 0.66, 0.72],
    secondary: [0.08, 0.22, 0.27],
    soft: [0.89, 0.96, 0.97],
    title: "teal",
  },
  invoice_clean_red: {
    accent: [0.84, 0.17, 0.18],
    secondary: [0.97, 0.62, 0.18],
    soft: [1, 0.96, 0.9],
    title: "red",
  },
  invoice_compact_navy: {
    accent: [0.17, 0.13, 0.31],
    secondary: [0.88, 0.39, 0.48],
    soft: [0.98, 0.9, 0.93],
    title: "navy",
  },
};

const BREAKDOWN_LABELS = {
  materialsSubtotal: ["Subtotal de materiales", "Materials subtotal"],
  laborSubtotal: ["Subtotal de mano de obra", "Labor subtotal"],
  equipmentSubtotal: ["Subtotal de equipos", "Equipment subtotal"],
  subcontractorsSubtotal: ["Subtotal de subcontratistas", "Subcontractors subtotal"],
  permitsFees: ["Permisos y tasas", "Permits and fees"],
  transport: ["Transporte", "Transport"],
  wasteManagement: ["Gestion de residuos", "Waste management"],
  overhead: ["Gastos generales", "Overhead"],
  contingency: ["Contingencia", "Contingency"],
  profit: ["Beneficio", "Profit"],
  discounts: ["Descuentos", "Discounts"],
};

export function createEstimatePdfBuffer(detail) {
  const estimate = detail.estimate;
  const version = detail.versions?.[0] || {};
  const snapshot = version.snapshot || {};
  const document = {
    documentLanguage: snapshot.documentLanguage || estimate.documentLanguage || "es",
    currency: snapshot.currency || estimate.currency || "USD",
    countryProfile: snapshot.countryProfile || estimate.countryProfile || "US",
  };
  const costBreakdown = estimate.costBreakdown || snapshot.costBreakdown || {};
  const company = estimate.companySnapshot || {};
  const project = estimate.projectSnapshot || snapshot.project || {};
  const title = label(document, "Cotizacion", "Estimate");
  const sections = detail.sections || [];
  const items = sections.flatMap((section) =>
    (section.items || []).map((item) => ({
      description: `${section.title}: ${item.description}`,
      quantity: item.quantity,
      unitCode: item.unitCode,
      unitPrice: item.unitPrice,
      totalAmount: item.totalAmount,
    })),
  );

  return buildDocumentPdf({
    templateId: estimate.templateId || snapshot.templateId || "estimate_classic_blue",
    title,
    number: estimate.estimateNumber,
    company,
    clientName: estimate.clientName,
    document,
    project,
    items,
    costBreakdown,
    totals: {
      subtotal: version.subtotalAmount || estimate.totalAmount,
      tax: version.taxAmount || 0,
      discount: costBreakdown.discounts?.amount || 0,
      total: version.totalAmount || estimate.totalAmount,
      balance: null,
    },
    notes: [
      snapshot.scope ? `${label(document, "Alcance", "Scope")}: ${snapshot.scope}` : "",
      snapshot.conditions ? `${label(document, "Condiciones", "Terms")}: ${snapshot.conditions}` : "",
      snapshot.exclusions ? `${label(document, "Exclusiones", "Exclusions")}: ${snapshot.exclusions}` : "",
    ].filter(Boolean),
    signature: company.signature?.name || company.companyName || company.legalName || "Empresa",
    complianceNote: label(
      document,
      "Cotizacion operativa. Los impuestos deben validarse segun la configuracion fiscal aplicable.",
      "Operational estimate. Taxes must be validated against the applicable tax configuration.",
    ),
  });
}

export function createInvoicePdfBuffer(detail) {
  const invoice = detail.invoice;
  const isCreditNote = invoice.invoiceType === "credit_note";
  const title = isCreditNote ? label(invoice, "Factura rectificativa", "Credit note") : label(invoice, "Factura", "Invoice");
  return buildDocumentPdf({
    templateId: invoice.templateId || "invoice_clean_red",
    title,
    number: invoice.invoiceNumber,
    company: invoice.companySnapshot || {},
    clientName: invoice.clientName,
    document: invoice,
    project: { name: invoice.jobTitle || "", address: "" },
    items: detail.items || [],
    costBreakdown: invoice.costBreakdown || {},
    totals: {
      subtotal: invoice.subtotalAmount,
      tax: invoice.taxAmount,
      discount: invoice.discountAmount,
      total: invoice.totalAmount,
      balance: invoice.balanceAmount,
    },
    notes: [
      `${label(invoice, "Fecha", "Date")}: ${invoice.issueDate || "-"}   ${label(invoice, "Vence", "Due")}: ${invoice.dueDate || "-"}`,
      invoice.correctionReason ? `${label(invoice, "Motivo rectificacion", "Correction reason")}: ${invoice.correctionReason}` : "",
    ].filter(Boolean),
    complianceNote: invoice.billingSnapshot?.complianceNote || "Operational document generated by Constriqo.",
  });
}

export function createReceiptPdfBuffer(detail, payment) {
  const invoice = detail.invoice;
  const receiptNumber = payment.receiptNumber || payment.reference || payment.paymentId;
  return buildDocumentPdf({
    templateId: invoice.templateId || "invoice_compact_navy",
    title: label(invoice, "Recibo de pago", "Payment receipt"),
    number: receiptNumber,
    company: invoice.companySnapshot || {},
    clientName: invoice.clientName,
    document: invoice,
    project: { name: invoice.invoiceNumber, address: "" },
    items: [
      {
        description: `${label(invoice, "Pago factura", "Invoice payment")} ${invoice.invoiceNumber}`,
        quantity: 1,
        unitCode: payment.method,
        unitPrice: payment.amount,
        totalAmount: payment.amount,
      },
    ],
    costBreakdown: {},
    totals: {
      subtotal: payment.amount,
      tax: 0,
      discount: 0,
      total: payment.amount,
      balance: invoice.balanceAmount,
    },
    notes: [
      `${label(invoice, "Fecha de pago", "Payment date")}: ${formatDateTime(payment.receivedAt)}`,
      `${label(invoice, "Referencia", "Reference")}: ${payment.reference || "-"}`,
    ],
    complianceNote: "Receipt generated from tenant-authenticated accounting records.",
  });
}

function buildDocumentPdf(input) {
  const style = TEMPLATE_STYLES[input.templateId] || TEMPLATE_STYLES.estimate_classic_blue;
  const commands = [];
  const doc = input.document || {};
  const companyLines = visibleCompanyLines(input.company || {});
  const title = `${input.title} ${input.number}`;
  let y = PAGE_HEIGHT - MARGIN;

  rect(commands, 0, 0, PAGE_WIDTH, PAGE_HEIGHT, [1, 1, 1]);
  rect(commands, 0, PAGE_HEIGHT - 118, PAGE_WIDTH, 118, style.soft);
  rect(commands, 0, PAGE_HEIGHT - 118, PAGE_WIDTH, 6, style.accent);
  rect(commands, PAGE_WIDTH - 270, PAGE_HEIGHT - 118, 270, 118, style.accent);
  rect(commands, PAGE_WIDTH - 78, PAGE_HEIGHT - 118, 78, 78, style.secondary);
  rect(commands, MARGIN, 52, PAGE_WIDTH - MARGIN * 2, 2, style.accent);

  text(commands, input.title.toUpperCase(), MARGIN, y, 21, [0.05, 0.08, 0.12]);
  y -= 26;
  text(commands, input.number || "-", MARGIN, y, 12, style.accent);
  y -= 24;
  text(commands, `${label(doc, "Cliente", "Client")}: ${input.clientName || "-"}`, MARGIN, y, 10, [0.08, 0.1, 0.14]);
  y -= 16;
  text(commands, `${label(doc, "Moneda", "Currency")}: ${doc.currency || "-"}   ${label(doc, "Pais", "Country")}: ${doc.countryProfile || "-"}`, MARGIN, y, 9, [0.22, 0.28, 0.36]);

  let rightY = PAGE_HEIGHT - MARGIN - 8;
  text(commands, input.company?.companyName || input.company?.legalName || "Constriqo", PAGE_WIDTH - 248, rightY, 12, [1, 1, 1]);
  rightY -= 16;
  for (const line of companyLines.slice(0, 5)) {
    text(commands, line, PAGE_WIDTH - 248, rightY, 8, [1, 1, 1], 176);
    rightY -= 12;
  }

  y = PAGE_HEIGHT - 152;
  if (input.project?.name || input.project?.address || input.project?.overview) {
    sectionHeader(commands, label(doc, "Proyecto / obra", "Project"), y, style);
    y -= 20;
    for (const line of [input.project.name, input.project.address, input.project.overview].filter(Boolean).slice(0, 3)) {
      text(commands, line, MARGIN, y, 9, [0.15, 0.18, 0.24], 510);
      y -= 13;
    }
    y -= 6;
  }

  sectionHeader(commands, label(doc, "Detalle", "Breakdown"), y, style);
  y -= 26;
  y = tableHeader(commands, y, style, doc);
  for (const item of input.items.slice(0, 13)) {
    y = tableRow(commands, y, item, doc);
    if (y < 230) {
      break;
    }
  }

  const breakdownRows = getBreakdownRows(input.costBreakdown || {}, doc);
  if (breakdownRows.length > 0 && y > 246) {
    y -= 14;
    sectionHeader(commands, label(doc, "Resumen profesional", "Professional summary"), y, style);
    y -= 20;
    for (const row of breakdownRows.slice(0, 12)) {
      text(commands, row.label, MARGIN, y, 8, [0.2, 0.24, 0.3], 250);
      text(commands, formatMoney(row.amount, doc.currency), 430, y, 8, [0.08, 0.1, 0.14], 100);
      y -= 12;
      if (y < 154) {
        break;
      }
    }
  }

  drawTotals(commands, input.totals, doc, style);

  let notesY = 142;
  for (const note of (input.notes || []).slice(0, 3)) {
    text(commands, note, MARGIN, notesY, 8, [0.18, 0.22, 0.28], 330);
    notesY -= 12;
  }

  if (input.signature) {
    line(commands, 386, 104, 540, 104, [0.65, 0.7, 0.76]);
    text(commands, label(doc, "Firma empresa", "Company signature"), 396, 116, 8, [0.25, 0.28, 0.34]);
    text(commands, input.signature, 398, 90, 9, [0.08, 0.1, 0.14], 130);
  }

  text(commands, input.complianceNote || "", MARGIN, 34, 7, [0.38, 0.42, 0.5], 455);
  text(commands, "Constriqo", PAGE_WIDTH - 110, 34, 8, style.accent);

  return createSinglePagePdf(commands.join("\n"), title);
}

function sectionHeader(commands, value, y, style) {
  rect(commands, MARGIN, y - 5, PAGE_WIDTH - MARGIN * 2, 18, style.accent);
  text(commands, value, MARGIN + 8, y, 9, [1, 1, 1]);
}

function tableHeader(commands, y, style, doc) {
  rect(commands, MARGIN, y - 6, PAGE_WIDTH - MARGIN * 2, 18, style.secondary);
  text(commands, label(doc, "Descripcion", "Description"), MARGIN + 8, y, 8, [1, 1, 1]);
  text(commands, label(doc, "Cantidad", "Qty"), 320, y, 8, [1, 1, 1]);
  text(commands, label(doc, "Precio", "Rate"), 390, y, 8, [1, 1, 1]);
  text(commands, label(doc, "Total", "Total"), 488, y, 8, [1, 1, 1]);
  return y - 20;
}

function tableRow(commands, y, item, doc) {
  text(commands, item.description || "-", MARGIN + 8, y, 8, [0.08, 0.1, 0.14], 250);
  text(commands, `${formatNumber(item.quantity)} ${item.unitCode || ""}`, 320, y, 8, [0.08, 0.1, 0.14], 62);
  text(commands, formatMoney(item.unitPrice, doc.currency), 390, y, 8, [0.08, 0.1, 0.14], 86);
  text(commands, formatMoney(item.totalAmount, doc.currency), 488, y, 8, [0.08, 0.1, 0.14], 80);
  line(commands, MARGIN, y - 5, PAGE_WIDTH - MARGIN, y - 5, [0.86, 0.88, 0.9]);
  return y - 16;
}

function drawTotals(commands, totals, doc, style) {
  const x = 360;
  let y = 188;
  const rows = [
    [label(doc, "Base imponible", "Taxable base"), totals.subtotal],
    [label(doc, "Impuestos", "Tax"), totals.tax],
    [label(doc, "Descuentos", "Discounts"), totals.discount],
  ];
  rect(commands, x - 8, y - 58, 210, 88, [0.96, 0.97, 0.98]);
  for (const [name, value] of rows) {
    text(commands, name, x, y, 8, [0.22, 0.26, 0.32]);
    text(commands, formatMoney(value, doc.currency), x + 104, y, 8, [0.08, 0.1, 0.14]);
    y -= 14;
  }
  rect(commands, x - 8, y - 8, 210, 20, style.accent);
  text(commands, label(doc, "TOTAL", "TOTAL"), x, y - 2, 10, [1, 1, 1]);
  text(commands, formatMoney(totals.total, doc.currency), x + 104, y - 2, 10, [1, 1, 1]);
  if (totals.balance !== null && totals.balance !== undefined) {
    text(commands, `${label(doc, "Saldo", "Balance")}: ${formatMoney(totals.balance, doc.currency)}`, x, y - 24, 8, [0.22, 0.26, 0.32]);
  }
}

function getBreakdownRows(input, doc) {
  if (!input?.enabled) {
    return [];
  }
  return Object.entries(BREAKDOWN_LABELS)
    .map(([key, labels]) => {
      const value = input[key] || {};
      return {
        label: value.label || (doc.documentLanguage === "en" ? labels[1] : labels[0]),
        amount: Number(value.amount || 0),
        applies: value.applies !== false,
      };
    })
    .filter((row) => row.applies && row.amount > 0);
}

function visibleCompanyLines(company) {
  const visibility = company.visibility || {};
  const show = (key) => visibility[key] !== false;
  const address = [company.address, company.city, company.region, company.postalCode].filter(Boolean).join(", ");
  return [
    show("legalName") ? company.legalName : "",
    show("taxId") ? company.taxId : "",
    show("contractorLicense") ? company.contractorLicense : "",
    show("address") ? address : "",
    show("phone") ? company.phone : "",
    show("email") ? company.email : "",
    show("website") ? company.website : "",
  ].filter(Boolean);
}

function rect(commands, x, y, width, height, rgb) {
  commands.push(`${rgb.join(" ")} rg`);
  commands.push(`${x} ${y} ${width} ${height} re f`);
}

function line(commands, x1, y1, x2, y2, rgb) {
  commands.push(`${rgb.join(" ")} RG`);
  commands.push(`0.8 w ${x1} ${y1} m ${x2} ${y2} l S`);
}

function text(commands, value, x, y, size, rgb, maxLength = 95) {
  commands.push(`${rgb.join(" ")} rg`);
  commands.push(`BT /F1 ${size} Tf ${x} ${y} Td (${escapePdfText(sanitizePdfText(value, maxLength))}) Tj ET`);
}

function createSinglePagePdf(contentStream, title) {
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(contentStream, "latin1")} >>\nstream\n${contentStream}\nendstream`,
    `<< /Title (${escapePdfText(sanitizePdfText(title))}) /Producer (Constriqo Runtime) >>`,
  ];
  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "latin1"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, "latin1");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info 6 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, "latin1");
}

function label(document, spanish, english) {
  return document.documentLanguage === "en" ? english : spanish;
}

function formatMoney(value, currency = "USD") {
  return `${currency} ${formatNumber(value)}`;
}

function formatNumber(value) {
  return Number(value || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function formatDateTime(value) {
  if (!value) {
    return "-";
  }
  return new Date(value).toISOString().slice(0, 10);
}

function sanitizePdfText(value, maxLength = 180) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\x20-\x7E]/g, " ")
    .slice(0, maxLength);
}

function escapePdfText(value) {
  return String(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}
